### ISSUE TITLE
App keeps crashing 

### ISSUE THREAD

**Issue by ellalaviolette** [j4nf4b3l/MDMPatcher-Universal#22]
Not allowing me to open it at all

**Comment by spald87** [comment]
same here, any ideas?

**Comment by heyitsgrace996** [comment]
Same for me. Ventura OS

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               MDMPatcher Universal [16356]
Path:                  /Volumes/VOLUME/*/MDMPatcher Universal.app/Contents/MacOS/MDMPatcher Universal
Identifier:            com.noone.mdmpatch
Version:               1.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-08-12 22:11:28.8828 +0100
OS Version:            macOS 13.5 (22G74)
Report Version:        12
Bridge OS Version:     7.6 (20P6072)
Anonymous UUID:        39DBF2D3-5D94-1C1E-9827-1F04E48B65A5

Sleep/Wake UUID:       20C4945E-0F0A-476B-BDE0-397ED6000FD2

Time Awake Since Boot: 21000 seconds
Time Since Wake:       224 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @loader_path/../Frameworks/libusbmuxd.dylib
Referenced from: <7D6F0D01-0364-314E-BEF5-EFCDEB0682EE> /Volumes/VOLUME/*/MDMPatcher Universal.app/Contents/MacOS/MDMPatcher Universal
Reason: tried: '/private/var/folders/5r/_v9884jd3pqf9rc8kgtj_dcm0000gn/T/AppTranslocation/821330BC-3313-4D16-A24D-649F7B849418/d/MDMPatcher Universal.app/Contents/MacOS/../Frameworks/libusbmuxd.dylib' (code signature in <C64B8859-B814-391D-B5DF-40098B9EEFEA> '/private/var/folders/5r/_v9884jd3pqf9rc8kgtj_dcm0000gn/T/AppTranslocation/821330BC-3313-4D16-A24D-649F7B849418/d/MDMPatcher Universal.app/Contents/Frameworks/libusbmuxd.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/libusbmuxd.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	    0x7ff80d86ec52 __abort_with_payload + 10
1   dyld                          	    0x7ff80d888fd7 abort_with_payload_wrapper_internal + 82
2   dyld                          	    0x7ff80d889009 abort_with_payload + 9
3   dyld                          	    0x7ff80d80d8f0 dyld4::halt(char const*) + 375
4   dyld                          	    0x7ff80d80ab71 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4526
5   dyld                          	    0x7ff80d8093bd start + 1805


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7b17a9358  rdx: 0x00007ff7b17a97c0
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7b17a93a0  rsp: 0x00007ff7b17a9358
   r8: 0x00007ff7b17a93c0   r9: 0x0000000000000000  r10: 0x00000000000000ee  r11: 0x0000000000000246
  r12: 0x00000000000000ee  r13: 0x00007ff7b17a97c0  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x00007ff80d86ec52  rfl: 0x0000000000000246  cr2: 0x000000010ecd6000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133


Binary Images:
       0x10e755000 -        0x10e7b0fff com.noone.mdmpatch (1.0) <7d6f0d01-0364-314e-bef5-efcdeb0682ee> /Volumes/VOLUME/*/MDMPatcher Universal.app/Contents/MacOS/MDMPatcher Universal
    0x7ff80d803000 -     0x7ff80d89b5ef dyld (*) <31e1c182-e611-3883-97a3-4334a21c90bd> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=171.9M resident=0K(0%) swapped_out_or_unallocated=171.9M(100%)
Writable regions: Total=8468K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8468K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                          8K        2 
__DATA                              59K        3 
__DATA_CONST                        20K        1 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       171.0M        3 
__TEXT                             980K        2 
dyld private memory                260K        2 
shared memory                        4K        1 
===========                     =======  ======= 
TOTAL                            236.3M       17 



-----------
Full Report
-----------

{"app_name":"MDMPatcher Universal","timestamp":"2023-08-12 22:11:29.00 +0100","app_version":"1.0","slice_uuid":"7d6f0d01-0364-314e-bef5-efcdeb0682ee","build_version":"1","platform":1,"bundleID":"com.noone.mdmpatch","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.5 (22G74)","roots_installed":0,"name":"MDMPatcher Universal","incident_id":"23FFD32A-DD36-4AF6-87C1-83A345F4ACFD"}
{
  "uptime" : 21000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro16,1",
  "coalitionID" : 3066,
  "osVersion" : {
    "train" : "macOS 13.5",
    "build" : "22G74",
    "releaseType" : "User"
  },
  "captureTime" : "2023-08-12 22:11:28.8828 +0100",
  "incident" : "23FFD32A-DD36-4AF6-87C1-83A345F4ACFD",
  "pid" : 16356,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-08-12 22:11:26.9371 +0100",
  "procStartAbsTime" : 21710478921539,
  "procExitAbsTime" : 21712424221020,
  "procName" : "MDMPatcher Universal",
  "procPath" : "\/Volumes\/VOLUME\/*\/MDMPatcher Universal.app\/Contents\/MacOS\/MDMPatcher Universal",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0","CFBundleVersion":"1","CFBundleIdentifier":"com.noone.mdmpatch"},
  "storeInfo" : {"deviceIdentifierForVendor":"7493652D-DB87-58D7-86D1-1D479BCD0A58","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.noone.mdmpatch",
  "crashReporterKey" : "39DBF2D3-5D94-1C1E-9827-1F04E48B65A5",
  "codeSigningID" : "com.noone.mdmpatch",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570503953,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 224,
  "bridgeVersion" : {"build":"20P6072","train":"7.6"},
  "sleepWakeUUID" : "20C4945E-0F0A-476B-BDE0-397ED6000FD2",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @loader_path\/..\/Frameworks\/libusbmuxd.dylib","Referenced from: <7D6F0D01-0364-314E-BEF5-EFCDEB0682EE> \/Volumes\/VOLUME\/*\/MDMPatcher Universal.app\/Contents\/MacOS\/MDMPatcher Universal","Reason: tried: '\/private\/var\/folders\/5r\/_v9884jd3pqf9rc8kgtj_dcm0000gn\/T\/AppTranslocation\/821330BC-3313-4D16-A24D-649F7B849418\/d\/MDMPatcher Universal.app\/Contents\/MacOS\/..\/Frameworks\/libusbmuxd.dylib' (code signature in <C64B8859-B814-391D-B5DF-40098B9EEFEA> '\/private\/var\/folders\/5r\/_v9884jd3pqf9rc8kgtj_dcm0000gn\/T\/AppTranslocation\/821330BC-3313-4D16-A24D-649F7B849418\/d\/MDMPatcher Universal.app\/Contents\/Frameworks\/libusbmuxd.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '\/usr\/lib\/libusbmuxd.dylib' (no such file, not in dyld cache)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":278279,"threadState":{"r13":{"value":140701811251136},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701811250112},"cr2":{"value":4543307776},"rdx":{"value":140701811251136},"r10":{"value":238},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":140703355563090,"matchesCrashFrame":1},"rbp":{"value":140701811250080},"rsp":{"value":140701811250008},"r12":{"value":238},"rcx":{"value":140701811250008},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":441426,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":1},{"imageOffset":548823,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":1},{"imageOffset":548873,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":43248,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":31601,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4526,"imageIndex":1},{"imageOffset":25533,"symbol":"start","symbolLocation":1805,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4537536512,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.noone.mdmpatch",
    "size" : 376832,
    "uuid" : "7d6f0d01-0364-314e-bef5-efcdeb0682ee",
    "path" : "\/Volumes\/VOLUME\/*\/MDMPatcher Universal.app\/Contents\/MacOS\/MDMPatcher Universal",
    "name" : "MDMPatcher Universal",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703355121664,
    "size" : 624112,
    "uuid" : "31e1c182-e611-3883-97a3-4334a21c90bd",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703354499072,
  "size" : 21474836480,
  "uuid" : "97012334-1dad-3407-9a6d-bf5805273339"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=171.9M resident=0K(0%) swapped_out_or_unallocated=171.9M(100%)\nWritable regions: Total=8468K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8468K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                              59K        3 \n__DATA_CONST                        20K        1 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       171.0M        3 \n__TEXT                             980K        2 \ndyld private memory                260K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                            236.3M       17 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "ec71137d5db4172d71f4db6e60556b74d7e7b9b0",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000055
    },
    {
      "rolloutId" : "61675b89201f677a9a4cbd65",
      "factorPackIds" : {
        "HEALTH_FEATURE_AVAILABILITY" : "64d14f3e1008ca2fac17a163"
      },
      "deploymentId" : 240000068
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000017
    },
    {
      "treatmentId" : "3a3cf641-8471-4e4e-9ad4-81d0ede970fd",
      "experimentId" : "64a84dae90d82611a0bd7d3d",
      "deploymentId" : 400000010
    }
  ]
}
}

Model: MacBookPro16,1, BootROM 1968.140.7.0.0 (iBridge: 20.16.6072.0.0,0), 8 processors, 8-Core Intel Core i9, 2.4 GHz, 32 GB, SMC 
Graphics: Intel UHD Graphics 630, Intel UHD Graphics 630, Built-In
Display: Color LCD, 3072 x 1920 Retina, Main, MirrorOff, Online
Graphics: AMD Radeon Pro 5500M, AMD Radeon Pro 5500M, PCIe, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 16 GB, DDR4, 2667 MHz, Micron, MT40A2G8NEA-062E:J
Memory Module: BANK 2/ChannelB-DIMM0, 16 GB, DDR4, 2667 MHz, Micron, MT40A2G8NEA-062E:J
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x7BF), wl0: Dec  9 2022 17:02:25 version 9.30.492.0.32.5.87 FWID 01-e7856862
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: Apple Mobile Device (Recovery Mode)
USB Device: T2Bus
USB Device: composite_device
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 63.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 63.5

**Comment by jonathan3195** [comment]
won't let me either

**Comment by j4nf4b3l** [comment]
Disable sip. Then try again.
